### ISSUE TITLE
Flag table appears below the flags

### ISSUE THREAD

**Issue by double-fault** [BrockA/SE-misc#1]
Regarding: https://github.com/BrockA/SE-misc/blob/master/Stack%20Exchange%2C%20Flagging%20tweaks.user.js

I just visited my flag summary page on Code Review, where I had only one flag, on a comment which was helpful. [I saw this](http://i.stack.imgur.com/bVyYK.png).

It was really weird, and I visited my other sites. On my top few sites, I did not find a single site with 1 flag as I'm pretty active in Spam Flagging in CharCoal. Luckily, I found my Photography profile had only one flag.

The US was working fine in my Photography Flag Summary page, and was surprised to see so. The only difference was that the flag on CodeReview was on a comment, while the one on Photography was a Spam flag.

I didn't visit all my profiles as it's pretty late here and I'm tired. Will do tomorrow and try to reproduce the problem. 

For now, I'm getting this bug on CodeReview.

**Comment by BrockA** [comment]
Yeah, I'm pretty sure this is related to the known issue as reported at http://stackapps.com/questions/7057/flagging-assistant-tweaks-for-frequent-flaggers .

I'll revisit it this weekend.

**Comment by BrockA** [comment]
Turns out this is a bug in the Code Review layout. It has nothing to do with this userscript.

See ["Flag summary layout broken"](http://meta.codereview.stackexchange.com/q/6771/28280), which is a reoccurrence of the earlier bug: ["Flagging history appears at the bottom of page"](http://meta.codereview.stackexchange.com/questions/6220/flagging-history-appears-at-the-bottom-of-page).
